
export const screens = {
  trail4: {
    r: 14,
    fontSize: 22,
    colors: {
      passed: 'green',
      pending: 'black',
      failed: 'red',
      label: 'black',
    },
    items: [
      {
        order: 1,
        cx: 160,
        cy: 205,
        label: '1',
      },
      {
        order: 2,
        cx: 205,
        cy: 70,
        label: '2',
      },
      {
        order: 3,
        cx: 295,
        cy: 210,
        label: '3',
      },
      {
        order: 4,
        cx: 230,
        cy: 145,
        label: '4',
      },
      {
        order: 5,
        cx: 240,
        cy: 260,
        label: '5',
      },
      {
        order: 6,
        cx: 55,
        cy: 270,
        label: '6',
      },
      {
        order: 7,
        cx: 35,
        cy: 140,
        label: '7',
      },
      {
        order: 8,
        cx: 130,
        cy: 105,
        label: '8',
      },
    ]
  },

  trail2: {
    r: 14,
    fontSize: 18,
    colors: {
      passed: 'green',
      pending: 'black',
      failed: 'red',
      label: 'black',
    },
    items: [
      {
        order: 1,
        cx: 225,
        cy: 190,
        label: '1',
      },
      {
        order: 2,
        cx: 140,
        cy: 230,
        label: '2',
      },
      {
        order: 3,
        cx: 250,
        cy: 235,
        label: '3',
      },
      {
        order: 4,
        cx: 235,
        cy: 130,
        label: '4',
      },
      {
        order: 5,
        cx: 125,
        cy: 150,
        label: '5',
      },
      {
        order: 6,
        cx: 175,
        cy: 167,
        label: '6',
      },
      {
        order: 7,
        cx: 110,
        cy: 195,
        label: '7',
      },
      {
        order: 8,
        cx: 70,
        cy: 255,
        label: '8',
      },
      {
        order: 9,
        cx: 88,
        cy: 295,
        label: '9',
      },
      {
        order: 10,
        cx: 110,
        cy: 250,
        label: '10',
      },
      {
        order: 11,
        cx: 200,
        cy: 300,
        label: '11',
      },
      {
        order: 12,
        cx: 45,
        cy: 310,
        label: '12',
      },
      {
        order: 13,
        cx: 60,
        cy: 165,
        label: '13',
      },
      {
        order: 14,
        cx: 35,
        cy: 205,
        label: '14',
      },
      {
        order: 15,
        cx: 35,
        cy: 40,
        label: '15',
      },
      {
        order: 16,
        cx: 60,
        cy: 95,
        label: '16',
      },
      {
        order: 17,
        cx: 165,
        cy: 30,
        label: '17',
      },
      {
        order: 18,
        cx: 137,
        cy: 105,
        label: '18',
      },
      {
        order: 19,
        cx: 260,
        cy: 70,
        label: '19',
      },
      {
        order: 20,
        cx: 195,
        cy: 70,
        label: '20',
      },
      {
        order: 21,
        cx: 290,
        cy: 25,
        label: '21',
      },
      {
        order: 22,
        cx: 290,
        cy: 120,
        label: '22',
      },
      {
        order: 23,
        cx: 300,
        cy: 315,
        label: '23',
      },
      {
        order: 24,
        cx: 282,
        cy: 175,
        label: '24',
      },
      {
        order: 25,
        cx: 265,
        cy: 295,
        label: '25',
      },
    ]
  },

  trail3: {
    r: 14,
    fontSize: 22,
    colors: {
      passed: 'green',
      pending: 'black',
      failed: 'red',
      label: 'black',
    },
    items: [
      {
        order: 1,
        cx: 145,
        cy: 200,
        label: '1',
      },
      {
        order: 2,
        cx: 220,
        cy: 77,
        label: 'A',
      },
      {
        order: 3,
        cx: 295,
        cy: 200,
        label: '2',
      },
      {
        order: 4,
        cx: 225,
        cy: 150,
        label: 'B',
      },
      {
        order: 5,
        cx: 230,
        cy: 255,
        label: '3',
      },
      {
        order: 6,
        cx: 70,
        cy: 255,
        label: 'C',
      },
      {
        order: 7,
        cx: 50,
        cy: 85,
        label: '4',
      },
      {
        order: 8,
        cx: 132,
        cy: 125,
        label: 'D',
      },
    ]
  },

  trail1: {
    r: 14,
    fontSize: 18,
    colors: {
      passed: 'green',
      pending: 'black',
      failed: 'red',
      label: 'black',
    },
    items: [
      {
        order: 1,
        cx: 95,
        cy: 180,
        label: '1',
      },
      {
        order: 2,
        cx: 190,
        cy: 57,
        label: 'A',
      },
      {
        order: 3,
        cx: 182,
        cy: 160,
        label: '2',
      },
      {
        order: 4,
        cx: 55,
        cy: 297,
        label: 'B',
      },
      {
        order: 5,
        cx: 125,
        cy: 65,
        label: '3',
      },
      {
        order: 6,
        cx: 55,
        cy: 32,
        label: 'C',
      },
      {
        order: 7,
        cx: 65,
        cy: 85,
        label: '4',
      },
      {
        order: 8,
        cx: 272,
        cy: 172,
        label: 'D',
      },
      {
        order: 9,
        cx: 232,
        cy: 145,
        label: '5',
      },
      {
        order: 10,
        cx: 267,
        cy: 95,
        label: 'E',
      },
      {
        order: 11,
        cx: 272,
        cy: 295,
        label: '6',
      },
      {
        order: 12,
        cx: 40,
        cy: 165,
        label: 'F',
      },
      {
        order: 13,
        cx: 45,
        cy: 220,
        label: '7',
      },
      {
        order: 14,
        cx: 20,
        cy: 65,
        label: 'G',
      },
      {
        order: 15,
        cx: 270,
        cy: 23,
        label: '8',
      },
      {
        order: 16,
        cx: 220,
        cy: 95,
        label: 'H',
      },
      {
        order: 17,
        cx: 135,
        cy: 150,
        label: '9',
      },
      {
        order: 18,
        cx: 295,
        cy: 240,
        label: 'I',
      },
      {
        order: 19,
        cx: 247,
        cy: 210,
        label: '10',
      },
      {
        order: 20,
        cx: 217,
        cy: 277,
        label: 'J',
      },
      {
        order: 21,
        cx: 92,
        cy: 242,
        label: '11',
      },
      {
        order: 22,
        cx: 307,
        cy: 120,
        label: 'K',
      },
      {
        order: 23,
        cx: 207,
        cy: 230,
        label: '12',
      },
      {
        order: 24,
        cx: 165,
        cy: 307,
        label: 'L',
      },
      {
        order: 25,
        cx: 135,
        cy: 227,
        label: '13',
      },
    ]
  },
}